#include "ArhqenCognitionEngine/Renderer/Scene/AceRenderScene.h"

#include <algorithm>
#include <cmath>

namespace am::renderer::scene
{
    namespace { float dot(Vec3 a,Vec3 b){return a.x*b.x+a.y*b.y+a.z*b.z;} Vec3 sub(Vec3 a,Vec3 b){return{a.x-b.x,a.y-b.y,a.z-b.z};} float len2(Vec3 v){return dot(v,v);} }
    Mat4 Identity(){Mat4 m;m.m={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};return m;}
    Mat4 Perspective(float f,float aspect,float zn,float zf){aspect=std::max(0.05f,aspect);zn=std::max(0.001f,zn);zf=std::max(zn+0.01f,zf);float y=1/std::tan(f*0.5f),x=y/aspect,z=zf/(zf-zn);Mat4 m;m.m={x,0,0,0,0,y,0,0,0,0,z,1,0,0,-zn*z,0};return m;}
    Bounds Merge(Bounds a,Bounds b){if(!a.valid)return b;if(!b.valid)return a;return{{std::min(a.min.x,b.min.x),std::min(a.min.y,b.min.y),std::min(a.min.z,b.min.z)},{std::max(a.max.x,b.max.x),std::max(a.max.y,b.max.y),std::max(a.max.z,b.max.z)},true};}
    Bounds Transform(Bounds b,Mat4 m){if(!b.valid)return{};Vec3 c[8]={{b.min.x,b.min.y,b.min.z},{b.max.x,b.min.y,b.min.z},{b.min.x,b.max.y,b.min.z},{b.max.x,b.max.y,b.min.z},{b.min.x,b.min.y,b.max.z},{b.max.x,b.min.y,b.max.z},{b.min.x,b.max.y,b.max.z},{b.max.x,b.max.y,b.max.z}};Bounds out;for(auto&p:c){float x=p.x*m.m[0]+p.y*m.m[4]+p.z*m.m[8]+m.m[12];float y=p.x*m.m[1]+p.y*m.m[5]+p.z*m.m[9]+m.m[13];float z=p.x*m.m[2]+p.y*m.m[6]+p.z*m.m[10]+m.m[14];out=Merge(out,{{x,y,z},{x,y,z},true});}return out;}
    void RenderScene::clear(){batches_.clear();}
    void RenderScene::add(MeshBatch b){if(!b.worldBounds.valid)b.worldBounds=Transform(b.mesh.bounds,b.localToWorld);batches_.push_back(std::move(b));}
    Bounds RenderScene::bounds()const{Bounds out;for(auto&b:batches_)out=Merge(out,b.worldBounds);return out;}
    bool SceneRenderer::visible(const MeshBatch& b,const View& v)const{if(!b.worldBounds.valid)return true;Vec3 c{(b.worldBounds.min.x+b.worldBounds.max.x)*.5f,(b.worldBounds.min.y+b.worldBounds.max.y)*.5f,(b.worldBounds.min.z+b.worldBounds.max.z)*.5f};return len2(sub(c,v.camera.position))<=v.camera.farPlane*v.camera.farPlane;}
    std::vector<const MeshBatch*> SceneRenderer::gather(const RenderScene& s,const View& v,Stats& st)const{std::vector<const MeshBatch*> out;st.submitted=s.count();for(auto&b:s.batches()){if(visible(b,v)){out.push_back(&b);++st.visible;if(b.transparent)++st.transparent;else++st.opaque;}else ++st.culled;}std::stable_sort(out.begin(),out.end(),[](auto*a,auto*b){if(a->transparent!=b->transparent)return !a->transparent;return a->name.value<b->name.value;});return out;}
    SceneRenderer::Build SceneRenderer::buildGraph(const RenderScene& s,const View& v,RenderGraph& g){Build out;auto vis=gather(s,v,out.stats);TextureDesc cd;cd.name=Name{"SceneColor"};cd.format=v.colorFormat;cd.extent={v.extent.width,v.extent.height,1};cd.usage=Usage::RenderTarget|Usage::ShaderResource;auto color=v.color.valid()?g.import(Name{"ImportedSceneColor"},v.color,cd):g.create(cd);TextureDesc dd;dd.name=Name{"SceneDepth"};dd.format=v.depthFormat;dd.extent={v.extent.width,v.extent.height,1};dd.usage=Usage::DepthStencil|Usage::ShaderResource;auto depth=v.depth.valid()?g.import(Name{"ImportedSceneDepth"},v.depth,dd):g.create(dd);auto p=g.addPass(Name{"BasePass"},Queue::Graphics,[this,vis,v](CommandList&cmd){recordBasePass(vis,v,cmd);});g.write(p,color,Access::RenderTarget);g.write(p,depth,Access::DepthWrite);out.stats.draws=static_cast<U32>(vis.size());out.ok=true;return out;}
    bool SceneRenderer::recordBasePass(const std::vector<const MeshBatch*>& vis,const View& v,CommandList& cmd)const{RenderPassDesc rp;rp.name=Name{"BasePass"};rp.extent=v.extent;if(v.color.valid())rp.colors.push_back({v.color,LoadOp::Clear,StoreOp::Store,{v.clear,1,0}});if(v.depth.valid())rp.depth=DepthAttachment{v.depth,LoadOp::Clear,StoreOp::Store,1,0};if(rp.colors.empty()&&!rp.depth)return true;cmd.begin(rp);cmd.viewport({0,0,(float)v.extent.width,(float)v.extent.height,0,1});cmd.scissor({0,0,v.extent.width,v.extent.height});for(auto*b:vis){if(!b||b->transparent)continue;cmd.pipeline(b->material.pipeline);cmd.vertexBuffer(0,b->mesh.vertices);if(b->mesh.indices.valid()&&b->mesh.indexCount) {cmd.indexBuffer(b->mesh.indices,b->mesh.indexFormat);cmd.drawIndexed(b->mesh.indexCount);} else cmd.draw(b->mesh.vertexCount);}cmd.end();return true;}
}
